export const countriesData = [
  //Africa:
    { country: "Africa de Sud", capital: "Pretoria, Cape Town, Bloemfontein", flag: "./src/assets/flags/south_africa.png" },
    { country: "Algeria", capital: "Alger", flag: "./src/assets/flags/algeria.png" },
    { country: "Angola", capital: "Luanda", flag: "./src/assets/flags/angola.png" },
    { country: "Benin", capital: "Cotonou, Porto Novo", flag: "./src/assets/flags/benin.png" },
    { country: "Botswana", capital: "Gaborone", flag: "./src/assets/flags/botswana.png" },
    { country: "Burundi", capital: "Gitega", flag: "./src/assets/flags/burundi.png" },
    { country: "Burkina Faso", capital: "Ouagadougou", flag: "./src/assets/flags/burkina_faso.png" },
    { country: "Camerun", capital: "Yaoundé", flag: "./src/assets/flags/cameroon.png" },
    { country: "Republica Capul Verde", capital: "Praia", flag: "./src/assets/flags/cape_verde.png" },
    { country: "Republica Centrafricană", capital: "Bangui", flag: "./src/assets/flags/car.png" },
    { country: "Ciad", capital: "N'Djamena", flag: "./src/assets/flags/chad.png" },
    { country: "Comore", capital: "Moroni", flag: "./src/assets/flags/comoros.png" },
    { country: "Republica Democratică Congo", capital: "Kinshasa", flag: "./src/assets/flags/drc.png" },
    { country: "Republica Congo", capital: "Brazzaville", flag: "./src/assets/flags/congo.png" },
    { country: "Coasta de Fildeș", capital: "Yamoussoukro", flag: "./src/assets/flags/cote_divoire.png" },
    { country: "Djibouti", capital: "Djibouti", flag: "./src/assets/flags/djibouti.png" },
    { country: "Egipt", capital: "Cairo", flag: "./src/assets/flags/egypt.png" },
    { country: "Eritreea", capital: "Asmara", flag: "./src/assets/flags/eritrea.png" },
    { country: "Etiopia", capital: "Addis Abeba", flag: "./src/assets/flags/ethiopia.png" },
    { country: "Eswatini", capital: "Mbabane, Lobamba", flag: "./src/assets/flags/eswatini.png" },
    { country: "Gabon", capital: "Libreville", flag: "./src/assets/flags/gabon.png" },
    { country: "Gambia", capital: "Banjul", flag: "./src/assets/flags/gambia.png" },
    { country: "Ghana", capital: "Accra", flag: "./src/assets/flags/ghana.png" },
    { country: "Guineea", capital: "Conakry", flag: "./src/assets/flags/guinea.png" },
    { country: "Guineea-Bissau", capital: "Bissau", flag: "./src/assets/flags/guinea_bissau.png" },
    { country: "Guineea Ecuatorială", capital: "Malabo", flag: "./src/assets/flags/equatorial_guinea.png" },
    { country: "Kenya", capital: "Nairobi", flag: "./src/assets/flags/kenya.png" },
    { country: "Lesotho", capital: "Maseru", flag: "./src/assets/flags/lesotho.png" },
    { country: "Liberia", capital: "Monrovia", flag: "./src/assets/flags/liberia.png" },
    { country: "Libia", capital: "Tripoli", flag: "./src/assets/flags/libya.png" },
    { country: "Madagascar", capital: "Antananarivo", flag: "./src/assets/flags/madagascar.png" },
    { country: "Malawi", capital: "Lilongwe", flag: "./src/assets/flags/malawi.png" },
    { country: "Mali", capital: "Bamako", flag: "./src/assets/flags/mali.png" },
    { country: "Mauritania", capital: "Nouakchott", flag: "./src/assets/flags/mauritania.png" },
    { country: "Mauritius", capital: "Port Louis", flag: "./src/assets/flags/mauritius.png" },
    { country: "Maroc", capital: "Rabat", flag: "./src/assets/flags/morocco.png" },
    { country: "Mozambic", capital: "Maputo", flag: "./src/assets/flags/mozambique.png" },
    { country: "Namibia", capital: "Windhoek", flag: "./src/assets/flags/namibia.png" },
    { country: "Niger", capital: "Niamey", flag: "./src/assets/flags/niger.png" },
    { country: "Nigeria", capital: "Abuja", flag: "./src/assets/flags/nigeria.png" },
    { country: "Rwanda", capital: "Kigali", flag: "./src/assets/flags/rwanda.png" },
    { country: "São Tomé și Príncipe", capital: "São Tomé", flag: "./src/assets/flags/sao_tome.png" },
    { country: "Senegal", capital: "Dakar", flag: "./src/assets/flags/senegal.png" },
    { country: "Sierra Leone", capital: "Freetown", flag: "./src/assets/flags/sierra_leone.png" },
    { country: "Somalia", capital: "Mogadishu", flag: "./src/assets/flags/somalia.png" },
    { country: "Sudan", capital: "Khartoum", flag: "./src/assets/flags/sudan.png" },
    { country: "Sudanul de Sud", capital: "Juba", flag: "./src/assets/flags/south_sudan.png" },
    { country: "Tanzania", capital: "Dar es Salaam, Dodoma", flag: "./src/assets/flags/tanzania.png" },
    { country: "Togo", capital: "Lomé", flag: "./src/assets/flags/togo.png" },
    { country: "Tunisia", capital: "Tunis", flag: "./src/assets/flags/tunisia.png" },
    { country: "Uganda", capital: "Kampala", flag: "./src/assets/flags/uganda.png" },
    { country: "Seychelles", capital: "Victoria", flag: "./src/assets/flags/seychelles.png" },
    { country: "Zambia", capital: "Lusaka", flag: "./src/assets/flags/zambia.png" },
    { country: "Zimbabwe", capital: "Harare", flag: "./src/assets/flags/zimbabwe.png" },

  //Asia:
    { country: "Afganistan", capital: "Kabul", flag: "./src/assets/flags/afghanistan.png" },
    { country: "Arabia Saudită", capital: "Riad", flag: "./src/assets/flags/saudi_arabia.png" },
    { country: "Azerbaidjan", capital: "Baku", flag: "./src/assets/flags/azerbaijan.png" },
    { country: "Bahrain", capital: "Manama", flag: "./src/assets/flags/bahrain.png" },
    { country: "Bangladesh", capital: "Dhaka", flag: "./src/assets/flags/bangladesh.png" },
    { country: "Bhutan", capital: "Thimphu", flag: "./src/assets/flags/bhutan.png" },
    { country: "Brunei", capital: "Bandar Seri Begawan", flag: "./src/assets/flags/brunei.png" },
    { country: "Cambodgia", capital: "Phnom Penh", flag: "./src/assets/flags/cambodia.png" },
    { country: "China", capital: "Beijing", flag: "./src/assets/flags/china.png" },
    { country: "Taiwan", capital: "Taipei", flag: "./src/assets/flags/taiwan.png" },
    { country: "Coreea de Nord", capital: "Phenian", flag: "./src/assets/flags/north_korea.png" },
    { country: "Coreea de Sud", capital: "Seul", flag: "./src/assets/flags/south_korea.png" },
    { country: "Emiratele Arabe Unite", capital: "Abu Dhabi", flag: "./src/assets/flags/uae.png" },
    { country: "India", capital: "New Delhi", flag: "./src/assets/flags/india.png" },
    { country: "Indonezia", capital: "Jakarta", flag: "./src/assets/flags/indonesia.png" },
    { country: "Iordania", capital: "Amman", flag: "./src/assets/flags/jordan.png" },
    { country: "Iran", capital: "Teheran", flag: "./src/assets/flags/iran.png" },
    { country: "Irak", capital: "Bagdad", flag: "./src/assets/flags/iraq.png" },
    { country: "Israel", capital: "Ierusalim", flag: "./src/assets/flags/israel.png" },
    { country: "Japonia", capital: "Tokyo", flag: "./src/assets/flags/japan.png" },
    { country: "Kazahstan", capital: "Astana", flag: "./src/assets/flags/kazakhstan.png" },
    { country: "Kârgâzstan", capital: "Bișkek", flag: "./src/assets/flags/kyrgyzstan.png" },
    { country: "Kuweit", capital: "Kuweit", flag: "./src/assets/flags/kuwait.png" },
    { country: "Laos", capital: "Vientiane", flag: "./src/assets/flags/laos.png" },
    { country: "Liban", capital: "Beirut", flag: "./src/assets/flags/lebanon.png" },
    { country: "Malaezia", capital: "Kuala Lumpur", flag: "./src/assets/flags/malaysia.png" },
    { country: "Maldive", capital: "Male", flag: "./src/assets/flags/maldives.png" },
    { country: "Mongolia", capital: "Ulan Bator", flag: "./src/assets/flags/mongolia.png" },
    { country: "Myanmar", capital: "Naypyidaw", flag: "./src/assets/flags/myanmar.png" },
    { country: "Nepal", capital: "Kathmandu", flag: "./src/assets/flags/nepal.png" },
    { country: "Oman", capital: "Muscat", flag: "./src/assets/flags/oman.png" },
    { country: "Pakistan", capital: "Islamabad", flag: "./src/assets/flags/pakistan.png" },
    { country: "Palestina", capital: "Ramala", flag: "./src/assets/flags/palestine.png" },
    { country: "Rusia", capital: "Moscova", flag: "./src/assets/flags/russia.png" },
    { country: "Filipine", capital: "Manila", flag: "./src/assets/flags/philippines.png" },
    { country: "Qatar", capital: "Doha", flag: "./src/assets/flags/qatar.png" },
    { country: "Singapore", capital: "Singapore", flag: "./src/assets/flags/singapore.png" },
    { country: "Sri Lanka", capital: "Sri Jayewardana Kotte, Colombo", flag: "./src/assets/flags/sri_lanka.png" },
    { country: "Siria", capital: "Damasc", flag: "./src/assets/flags/syria.png" },
    { country: "Tadjikistan", capital: "Dușanbe", flag: "./src/assets/flags/tajikistan.png" },
    { country: "Thailanda", capital: "Bangkok", flag: "./src/assets/flags/thailand.png" },
    { country: "Timorul de Est", capital: "Dili", flag: "./src/assets/flags/east_timor.png" },
    { country: "Turcia", capital: "Ankara", flag: "./src/assets/flags/turkey.png" },
    { country: "Turkmenistan", capital: "Așgabat", flag: "./src/assets/flags/turkmenistan.png" },
    { country: "Uzbekistan", capital: "Tașkent", flag: "./src/assets/flags/uzbekistan.png" },
    { country: "Vietnam", capital: "Hanoi", flag: "./src/assets/flags/vietnam.png" },
    { country: "Yemen", capital: "Sana'a", flag: "yemen./src/assets/flags/.png" },

  //Europe:
    { country: "Albania", capital: "Tirana", flag: "./src/assets/flags/albania.png" },
    { country: "Andorra", capital: "Andorra la Vella", flag: "./src/assets/flags/andorra.png" },
    { country: "Armenia", capital: "Erevan", flag: "./src/assets/flags/armenia.png" },
    { country: "Austria", capital: "Viena", flag: "./src/assets/flags/austria.png" },
    { country: "Belarus", capital: "Minsk", flag: "./src/assets/flags/belarus.png" },
    { country: "Belgia", capital: "Bruxelles", flag: "./src/assets/flags/belgium.png" },
    { country: "Bosnia și Herțegovina", capital: "Sarajevo", flag: "./src/assets/flags/bosnia.png" },
    { country: "Bulgaria", capital: "Sofia", flag: "./src/assets/flags/bulgaria.png" },
    { country: "Cehia", capital: "Praga", flag: "./src/assets/flags/czech_republic.png" },
    { country: "Cipru", capital: "Nicosia", flag: "./src/assets/flags/cyprus.png" },
    { country: "Croația", capital: "Zagreb", flag: "./src/assets/flags/croatia.png" },
    { country: "Danemarca", capital: "Copenhaga", flag: "./src/assets/flags/denmark.png" },
    { country: "Elveția", capital: "Berna", flag: "./src/assets/flags/switzerland.png" },
    { country: "Estonia", capital: "Tallinn", flag: "./src/assets/flags/estonia.png" },
    { country: "Finlanda", capital: "Helsinki", flag: "./src/assets/flags/finland.png" },
    { country: "Franța", capital: "Paris", flag: "./src/assets/flags/france.png" },
    { country: "Germania", capital: "Berlin", flag: "./src/assets/flags/germany.png" },
    { country: "Georgia", capital: "Tbilisi", flag: "./src/assets/flags/georgia.png" },
    { country: "Grecia", capital: "Atena", flag: "./src/assets/flags/greece.png" },
    { country: "Irlanda", capital: "Dublin", flag: "./src/assets/flags/ireland.png" },
    { country: "Italia", capital: "Roma", flag: "./src/assets/flags/italy.png" },
    { country: "Islanda", capital: "Reykjavik", flag: "./src/assets/flags/iceland.png" },
    { country: "Kosovo", capital: "Priștina", flag: "./src/assets/flags/kosovo.png" },
    { country: "Letonia", capital: "Riga", flag: "./src/assets/flags/latvia.png" },
    { country: "Liechtenstein", capital: "Vaduz", flag: "./src/assets/flags/liechtenstein.png" },
    { country: "Lituania", capital: "Vilnius", flag: "./src/assets/flags/lithuania.png" },
    { country: "Luxemburg", capital: "Luxemburg", flag: "./src/assets/flags/luxembourg.png" },
    { country: "Macedonia de Nord", capital: "Skopje", flag: "./src/assets/flags/north_macedonia.png" },
    { country: "Malta", capital: "La Valletta", flag: "./src/assets/flags/malta.png" },
    { country: "Republica Moldova", capital: "Chișinău", flag: "./src/assets/flags/moldova.png" },
    { country: "Monaco", capital: "Monaco", flag: "./src/assets/flags/monaco.png" },
    { country: "Muntenegru", capital: "Podgorița", flag: "./src/assets/flags/montenegro.png" },
    { country: "Norvegia", capital: "Oslo", flag: "./src/assets/flags/norway.png" },
    { country: "Polonia", capital: "Varșovia", flag: "./src/assets/flags/poland.png" },
    { country: "Portugalia", capital: "Lisabona", flag: "./src/assets/flags/portugal.png" },
    { country: "Regatul Unit", capital: "Londra", flag: "./src/assets/flags/uk.png" },
    { country: "România", capital: "București", flag: "./src/assets/flags/romania.png" },
    { country: "Rusia", capital: "Moscova", flag: "./src/assets/flags/russia.png" },
    { country: "San Marino", capital: "San Marino", flag: "./src/assets/flags/san_marino.png" },
    { country: "Scoția", capital: "Edinburgh", flag: "./src/assets/flags/scotland.png" },
    { country: "Serbia", capital: "Belgrad", flag: "./src/assets/flags/serbia.png" },
    { country: "Slovacia", capital: "Bratislava", flag: "./src/assets/flags/slovakia.png" },
    { country: "Slovenia", capital: "Ljubljana", flag: "./src/assets/flags/slovenia.png" },
    { country: "Spania", capital: "Madrid", flag: "./src/assets/flags/spain.png" },
    { country: "Suedia", capital: "Stockholm", flag: "./src/assets/flags/sweden.png" },
    { country: "Țările de Jos", capital: "Amsterdam, Haga", flag: "./src/assets/flags/netherlands.png" },
    { country: "Ucraina", capital: "Kiev", flag: "./src/assets/flags/ukraine.png" },
    { country: "Ungaria", capital: "Budapesta", flag: "./src/assets/flags/hungary.png" },
    { country: "Vatican", capital: "Vatican", flag: "./src/assets/flags/vatican.png" },
    { country: "Țara Galilor", capital: "Cardiff", flag: "./src/assets/flags/wales.png" },

  //North America:
    { country: "Antigua și Barbuda", capital: "Sfântul John", flag: "./src/assets/flags/antigua.png" },
    { country: "Bahamas", capital: "Nassau", flag: "./src/assets/flags/bahamas.png" },
    { country: "Barbados", capital: "Bridgetown", flag: "./src/assets/flags/barbados.png" },
    { country: "Belize", capital: "Belmopan", flag: "./src/assets/flags/belize.png" },
    { country: "Canada", capital: "Ottawa", flag: "./src/assets/flags/canada.png" },
    { country: "Costa Rica", capital: "San José", flag: "./src/assets/flags/costa_rica.png" },
    { country: "Cuba", capital: "Havana", flag: "./src/assets/flags/cuba.png" },
    { country: "Dominica", capital: "Roseau", flag: "./src/assets/flags/dominica.png" },
    { country: "Republica Dominicană", capital: "Sfântul Dominigo", flag: "./src/assets/flags/dominican_republic.png" },
    { country: "El Salvador", capital: "San Salvador", flag: "./src/assets/flags/el_salvador.png" },
    { country: "Grenada", capital: "Sfântul George", flag: "./src/assets/flags/grenada.png" },
    { country: "Groenlanda", capital: "Nuuk", flag: "./src/assets/flags/greenland.png" },
    { country: "Guatemala", capital: "Guatemala", flag: "./src/assets/flags/guatemala.png" },
    { country: "Haiti", capital: "Port au Prince", flag: "./src/assets/flags/haiti.png" },
    { country: "Honduras", capital: "Tegucigalpa", flag: "./src/assets/flags/honduras.png" },
    { country: "Jamaica", capital: "Kingston", flag: "./src/assets/flags/jamaica.png" },
    { country: "Mexic", capital: "Ciudad de México", flag: "./src/assets/flags/mexico.png" },
    { country: "Nicaragua", capital: "Managua", flag: "./src/assets/flags/nicaragua.png" },
    { country: "Panama", capital: "Panama", flag: "./src/assets/flags/panama.png" },
    { country: "Sfântul Cristofor și Nevis", capital: "Basseterre", flag: "./src/assets/flags/skn.png" },
    { country: "Sfânta Lucia", capital: "Castries", flag: "./src/assets/flags/st_lucia.png" },
    { country: "Sfântul Vincențiu și Grenadinele", capital: "Kingstown", flag: "./src/assets/flags/st_vincent.png" },
    { country: "Statele Unite ale Americii", capital: "Washington, D.C.", flag: "./src/assets/flags/usa.png" },
    { country: "Trinidad și Tobago", capital: "Port Spania", flag: "./src/assets/flags/trinidad.png" },
    { country: "Insula Sfântul Martin", capital: "Marigot", flag: "./src/assets/flags/st_martin.png" },
    { country: "Puerto Rico", capital: "San Juan", flag: "./src/assets/flags/puerto_rico.png" },
    { country: "Sfântul Eustasie", capital: "Oranjestad (Sf. Eust.)", flag: "./src/assets/flags/st_eustatius.png" },
    { country: "Saba", capital: "The Bottom", flag: "./src/assets/flags/saba.png" },
    { country: "Curaçao", capital: "Willemstad", flag: "./src/assets/flags/curacao.png" },
    { country: "Insula Bonaire", capital: "Kralendijk", flag: "./src/assets/flags/bonaire.png" },
    { country: "Aruba", capital: "Oranjestad (Aruba)", flag: "./src/assets/flags/aruba.png" },
    { country: "Guadelupa", capital: "Basse-Terre", flag: "./src/assets/flags/guadeloupe.png" },

  //Oceania:
    { country: "Australia", capital: "Canberra", flag: "./src/assets/flags/australia.png" },
    { country: "Fiji", capital: "Suva", flag: "./src/assets/flags/fiji.png" },
    { country: "Kiribati", capital: "Tarawa", flag: "./src/assets/flags/kiribati.png" },
    { country: "Insulele Marshall", capital: "Majuro", flag: "./src/assets/flags/marshall.png" },
    { country: "Micronezia", capital: "Palikir", flag: "./src/assets/flags/micronesia.png" },
    { country: "Nauru", capital: "Yaren", flag: "./src/assets/flags/nauru.png" },
    { country: "Noua Zeelandă", capital: "Wellington", flag: "./src/assets/flags/new_zealand.png" },
    { country: "Palau", capital: "Ngerulmud", flag: "./src/assets/flags/palau.png" },
    { country: "Papua Noua Guinee", capital: "Port Moresby", flag: "./src/assets/flags/png.png" },
    { country: "Samoa", capital: "Apia", flag: "./src/assets/flags/samoa.png" },
    { country: "Insulele Solomon", capital: "Honiara", flag: "./src/assets/flags/solomon.png" },
    { country: "Tonga", capital: "Nuku'alofa", flag: "./src/assets/flags/tonga.png" },
    { country: "Tuvalu", capital: "Funafuti", flag: "./src/assets/flags/tuvalu.png" },
    { country: "Vanuatu", capital: "Port Vila", flag: "./src/assets/flags/vanuatu.png" },
    { country: "Noua Caledonie", capital: "Nouméa", flag: "./src/assets/flags/new_caledonia.png" },
    { country: "Insula Niue", capital: "Alofi", flag: "./src/assets/flags/niue.png" },

  //South America:
    { country: "Argentina", capital: "Buenos Aires", flag: "./src/assets/flags/argentina.png" },
    { country: "Bolivia", capital: "La Paz, Sucre", flag: "./src/assets/flags/bolivia.png" },
    { country: "Brazilia", capital: "Brasília", flag: "./src/assets/flags/brazil.png" },
    { country: "Chile", capital: "Santiago", flag: "./src/assets/flags/chile.png" },
    { country: "Columbia", capital: "Bogotá", flag: "./src/assets/flags/colombia.png" },
    { country: "Ecuador", capital: "Quito", flag: "./src/assets/flags/ecuador.png" },
    { country: "Guyana", capital: "Georgetown", flag: "./src/assets/flags/guyana.png" },
    { country: "Paraguay", capital: "Asunción", flag: "./src/assets/flags/paraguay.png" },
    { country: "Peru", capital: "Lima", flag: "./src/assets/flags/peru.png" },
    { country: "Surinam", capital: "Paramaribo", flag: "./src/assets/flags/suriname.png" },
    { country: "Uruguay", capital: "Montevideo", flag: "./src/assets/flags/uruguay.png" },
    { country: "Venezuela", capital: "Caracas", flag: "./src/assets/flags/venezuela.png" },
  ];
  
  export const countiesData = [
    { judet: "Alba", resedinta: "Alba Iulia" },
    { judet: "Arad", resedinta: "Arad" },
    { judet: "Argeș", resedinta: "Pitești" },
    { judet: "Bacău", resedinta: "Bacău" },
    { judet: "Bihor", resedinta: "Oradea" },
    { judet: "Bistrița-Năsăud", resedinta: "Bistrița" },
    { judet: "Botoșani", resedinta: "Botoșani" },
    { judet: "Brașov", resedinta: "Brașov" },
    { judet: "Brăila", resedinta: "Brăila" },
    { judet: "Ilfov", resedinta: "București" },
    { judet: "Buzău", resedinta: "Buzău" },
    { judet: "Caraș-Severin", resedinta: "Reșița" },
    { judet: "Călărași", resedinta: "Călărași" },
    { judet: "Cluj", resedinta: "Cluj-Napoca" },
    { judet: "Constanța", resedinta: "Constanța" },
    { judet: "Covasna", resedinta: "Sfântu Gheorghe" },
    { judet: "Dâmbovița", resedinta: "Târgoviște" },
    { judet: "Dolj", resedinta: "Craiova" },
    { judet: "Galați", resedinta: "Galați" },
    { judet: "Giurgiu", resedinta: "Giurgiu" },
    { judet: "Gorj", resedinta: "Târgu Jiu" },
    { judet: "Harghita", resedinta: "Miercurea-Ciuc" },
    { judet: "Hunedoara", resedinta: "Deva" },
    { judet: "Ialomița", resedinta: "Slobozia" },
    { judet: "Iași", resedinta: "Iași" },
    { judet: "Maramureș", resedinta: "Baia Mare" },
    { judet: "Mehedinți", resedinta: "Drobeta-Turnu Severin" },
    { judet: "Mureș", resedinta: "Târgu Mureș" },
    { judet: "Neamț", resedinta: "Piatra Neamț" },
    { judet: "Olt", resedinta: "Slatina" },
    { judet: "Prahova", resedinta: "Ploiești" },
    { judet: "Satu Mare", resedinta: "Satu Mare" },
    { judet: "Sălaj", resedinta: "Zalău" },
    { judet: "Sibiu", resedinta: "Sibiu" },
    { judet: "Suceava", resedinta: "Suceava" },
    { judet: "Teleorman", resedinta: "Alexandria" },
    { judet: "Timiș", resedinta: "Timișoara" },
    { judet: "Tulcea", resedinta: "Tulcea" },
    { judet: "Vâlcea", resedinta: "Râmnicu Vâlcea" },
    { judet: "Vrancea", resedinta: "Focșani" },
  ];